### ISSUE TITLE
Error regarding package “libgnutls-openssl-dev” and changes in documentation.

### ISSUE THREAD

**Issue by andrewkamble88** [gnss-sdr/geniuss-place#25]
As I was installing GNSS-SDR on my local machine (Ubuntu 18.04 LTS) by referring documentation for “Build and Install” section, while installing dependencies using packages ,I came across to error regarding “libgnutls-openssl-dev” package and that in turn resulted into segmentation fault while running .conf file. 
As Ubuntu 18.04 and above requires particular version name  i.e “libgnutls28-dev” instead of “libgnutls-openssl-dev” for installing GNU TLS library.
I am sending pull request regarding changes in the same.I have added extra section in “03-build-and-install.md” file for installing dependencies using packages for  “Ubuntu 18.04 and above” in “Build and Install” in documentation on website.
Thank You!

**Comment by carlesfernandez** [comment]
Dear @andrewkamble88 

from what I see, `libgnutls-openssl-dev` is a virtual package that installs what you need in all Ubuntu versions. In Ubuntu 18.04, it installs `libgnutls28-dev` while in older versions (e.g., Ubuntu 14.04) it installs `libgnutls-dev`.

Check https://packages.ubuntu.com/bionic/libgnutls-openssl-dev for the details.

I prefer to keep the name `libgnutls-openssl-dev`, so the same line serves to all Ubuntu users.

The segmentation fault you got is probably due to a wrong configuration, since the software does not build if gnutls or openssl are not found in your system. Please post the error you got in an issue at https://github.com/gnss-sdr/gnss-sdr/issues to get help.

Thanks for your interest.

**Comment by andrewkamble88** [comment]
Thank you for your reply. The error has gone as I installed libgnutls28-dev package manually. I think in some machines(Ubuntu 18.04 or above) it automatically selects and installs libgnutls28-dev instead of libgnutls-openssl-dev. I have executed .conf file with both raw data files “2013_04_04_GNSS_SIGNAL_at_and “gps_l2c_m_prn7_5msps.dat”.
Regards,
Andrew Kamble
